---
- hosts: webservers
  become: yes
  vars:
    image_name: "janhavi001/nodejs-cloud-app"
    image_tag: "{{ ansible_env.GIT_COMMIT | default('latest') }}"
  
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    
    - name: Install pip
      apt:
        name: python3-pip
        state: present
    
    - name: Install Docker Python library
      pip:
        name: docker
        state: present
    
    - name: Pull Docker image
      docker_image:
        name: "{{ image_name }}:{{ image_tag }}"
        source: pull
    
    - name: Stop existing container
      docker_container:
        name: nodejs-app
        state: stopped
      ignore_errors: yes
    
    - name: Remove existing container
      docker_container:
        name: nodejs-app
        state: absent
      ignore_errors: yes
    
    - name: Run new container
      docker_container:
        name: nodejs-app
        image: "{{ image_name }}:{{ image_tag }}"
        ports:
          - "3000:3000"
        restart_policy: unless-stopped